server:
  port: 9003

spring:
  application:
    name: save-order

# \u914D\u7F6E\u670D\u52A1\u4E0E\u53D1\u73B0\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

